package com.yst.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBusinesses<M extends BaseBusinesses<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setSite(java.lang.String site) {
		set("site", site);
	}
	
	public java.lang.String getSite() {
		return getStr("site");
	}

	public void setLoginName(java.lang.String loginName) {
		set("loginName", loginName);
	}
	
	public java.lang.String getLoginName() {
		return getStr("loginName");
	}

	public void setLoginPwd(java.lang.String loginPwd) {
		set("loginPwd", loginPwd);
	}
	
	public java.lang.String getLoginPwd() {
		return getStr("loginPwd");
	}

	public void setBusinName(java.lang.String businName) {
		set("businName", businName);
	}
	
	public java.lang.String getBusinName() {
		return getStr("businName");
	}

}
