package com.yst.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseApp<M extends BaseApp<M>> extends Model<M> implements IBean {

	public void setAppid(java.lang.String appid) {
		set("appid", appid);
	}
	
	public java.lang.String getAppid() {
		return getStr("appid");
	}

	public void setAppsecert(java.lang.String appsecert) {
		set("appsecert", appsecert);
	}
	
	public java.lang.String getAppsecert() {
		return getStr("appsecert");
	}

	public void setAppname(java.lang.String appname) {
		set("appname", appname);
	}
	
	public java.lang.String getAppname() {
		return getStr("appname");
	}

}
