package com.yst.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVoucher<M extends BaseVoucher<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setNumber(java.lang.String number) {
		set("number", number);
	}
	
	public java.lang.String getNumber() {
		return getStr("number");
	}

	public void setMoney(java.lang.String money) {
		set("money", money);
	}
	
	public java.lang.String getMoney() {
		return getStr("money");
	}

	public void setMonetary(java.lang.String monetary) {
		set("monetary", monetary);
	}
	
	public java.lang.String getMonetary() {
		return getStr("monetary");
	}

	public void setMerchandises(java.lang.String merchandises) {
		set("merchandises", merchandises);
	}
	
	public java.lang.String getMerchandises() {
		return getStr("merchandises");
	}

	public void setBusinessesId(java.lang.Integer businessesId) {
		set("businessesId", businessesId);
	}
	
	public java.lang.Integer getBusinessesId() {
		return getInt("businessesId");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}
	
	public java.lang.String getState() {
		return getStr("state");
	}

	public void setExplains(java.lang.String explains) {
		set("explains", explains);
	}
	
	public java.lang.String getExplains() {
		return getStr("explains");
	}

}
